name: CI Pipeline
on: [push]
jobs:
  build:
    runs-on: [self-hosted, redhat]
    strategy:
      matrix:
        maven: [ '3.9.9' ]
    name: Maven ${{ matrix.maven }} sample
    steps:
      - name: Install dependencies
        run: yum install -y java maven
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.9.0
        with:
          java-version: 8
          maven-version: ${{ matrix.maven }}
      - name: Install dependencies
        run: mvn clean install
